global:
  scrape_interval: 15s # Scrape metrics every 15 seconds
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9091'] # Scrape Prometheus itself
  - job_name: 'thingsboard-pe'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['thingsboard.local'] # Scrape your app service